### PR TITLE
Bucket defs (for review and contribution)

### PR DESCRIPTION
**Pull request by argyleink**
let's hack on this together!

To Do:
- [ ] define CSS3 (and it's exceptional definition)
- [ ] dates need defined

### CODE REVIEW

**Comment by pp-koch** [comment]
My definitions:

CSS3
These are the features defined in 2009 as being part of CSS3. 
[Do not change definition]

CSS4
CSS features that were not part of CSS3 but are necessary to understand and use CSS on a professional level today.

CSS5
Things To Watch. CSS features that are not quite ready yet, but that promise to have a high impact on how CSS is used. 

CSS6
All other features.

Once we start on CSS5 we'll up all version numbers by one.

Opinion: Don't refer to dates.

**Comment by Que-tin** [comment]
I'll add up on @pp-koch's answer.

To make this clear, these are the definitions for todays standpoint, these aren't universal time independent definitions, but only for the sake of the survey. So there is no need to overcomplicate things because of how these definitions won't work in x year from now imo. There also isn't a universal definition for CSS3 that explains it in a short matter and excludes all features that got added since then.

### CSS4
> Essential CSS features that were not part of CSS3 but are already fundamental part of the everyday life of most developers on a professional level.

I would try to leave out words like _necessary_ because they are too subjective. With the definition above I'm trying to be as objective as possible but still trying to give a brief context.

### CSS5
> Newer features that previously landed whose adoption is steadily growing.

I think, if we agree upon that we are currently in CSS5, this is the definition for most of the features we are trying to put under that umbrella

### CSS6
> Experimental and not widely supported features, that are planned to be implemented into all browsers.

I wouldn't per se say that all other features are CSS6, I wouldn't put stuff into that bucket where it's not clear how, when or if they'll ever become widely available across all browsers.

**Comment by una** [comment]
Discussion in #86

**Comment by una** [comment]
Resolved in August 21, 2023 meeting:

**CSS3 (~2009-2012)**
Level 3 CSS specs as defined by the CSSWG.

**CSS4 (~2013-2018)**
Essential features that were not part of CSS3 but are already a fundamental part of CSS.

**CSS5 (~2019-2024)**
Newer features whose adoption is steadily growing.

**CSS6 (~2024+)**
Early-stage features that are planned for future CSS.

Note: Likely won't include CSS6 in survey, but will in initial materials. Will have "I don't know this feature" for the survey instead

**Pull request closed without merging**
